### ISSUE TITLE
Binary Tree Error.

### ISSUE THREAD

**Issue by LittleTasteOfHeaven** [satvik-1203/ds-visualizer#64]
![image](https://user-images.githubusercontent.com/93582436/140617298-43568da7-6f5c-4d7a-9dba-fd014e0e3216.png)

**Comment by satvik-1203** [comment]
sheesh, can you tell me what caused that error cuz I thought I handled it right

**Comment by satvik-1203** [comment]
lemme fix it tho, It's just a null ref error :), thanks for bringing it to my notice

**Comment by satvik-1203** [comment]
I fixed the bug, so if u see that again lemme know. but I'm curious why that broke haha

**Comment by LittleTasteOfHeaven** [comment]
Thanks. I encountered the error when I was adding nodes to the tree, and it crashed. Glad it fixed good job :+1:

**Comment by satvik-1203** [comment]
> Thanks. I encountered the error when I was adding nodes to the tree, and it crashed. Glad it fixed good job :+1: 

Did u test it? Just wanna make sure it works :)

**Comment by LittleTasteOfHeaven** [comment]
It works fine as of now. I will reopen the issue if it crashes again :+1:
